### ISSUE TITLE
Potential issue in max_iou computation

### ISSUE THREAD

**Issue by yuwen-lu** [ktrk115/const_layout#18]
I have a question regarding the implementation of max_iou computation in the following file:

https://github.com/ktrk115/const_layout/blob/5287480505939345543fff0b9f2e5d541e6f84e2/metric.py#LL92C9-L92C21

For line 92:         n = len(_bi)

In my understanding, if we simply take len(_bi), when _bj contains more elements than _bi and when in _bj there are elements beyond index n that match better with elements in _bi, these elements are ignored and thus producing sub-optimal max_iou calculations.

Would it be a better solution to create a len(_bi) by len(_bj) mesh, and handle non-square matrices as follows?

**Comment by ktrk115** [comment]
Thank you for your question! And sorry for the late response.

This function assumes that the two input layouts have the same label set and that `_bi` and `_bj` are bbox sequences of the same length, i.e., both have the same number of a specific type of elements. The code for creating two sets of layouts that have the same label set can be found [here](https://github.com/ktrk115/const_layout/blob/5287480505939345543fff0b9f2e5d541e6f84e2/metric.py#L126-L131).

**Comment by yuwen-lu** [comment]
Thanks for the explanation! 

But since the code took an intersection between the 2 key sets (line 130), it seems like only the shared labels and their bounding boxes are considered in computing the max iou? My question is largely, what happens when the generated result has different quantity of keys/bounding boxes?

**Comment by ktrk115** [comment]
Yes, we can only compute the max iou with the shared labels and their bounding boxes. Since our problem setting is label-conditioned layout generation, we evaluated the models with given labels, i.e., using the same labels as the test set (see [generation code](https://github.com/ktrk115/const_layout/blob/5287480505939345543fff0b9f2e5d541e6f84e2/generate.py#L60-L65)).

For different quantities of keys (layouts?) or bounding boxes, the max iou becomes ill-defined and would cause unwanted behavior such as ignoring partial boxes.

**Comment by yuwen-lu** [comment]
Aha, that makes a lot of sense, thank you! 

I was confused because another paper cited your work but didn't mention the label-conditioned part in their approach. They didn't open source their code so I came here. 

Thanks for your explanation!
